import type { Project } from '@src/types/proyects';

export const projects: Project[] = [
  {
    image: 'api.webp',
    title: 'API REST',
    description: 'API REST con autenticación y endpoints documentados.',
    date: 'Mar 2026',
    type: 'Proyecto personal',
    client: 'Uso interno',
    duration: '3 meses',
    teamSize: 'Solo',
    stack: ['Node.js', 'Express', 'PostgreSQL', 'JWT', 'Docker', 'Swagger'],
    architecture: 'Arquitectura en capas (MVC) con separación de responsabilidades por módulo.',
    integrations: ['JWT para auth', 'Docker para deploy', 'Swagger para documentación'],
    role: 'Desarrollador Full Stack — diseñé la arquitectura, implementé auth y documenté endpoints.',
    responsibilities: ['Diseño de la arquitectura de rutas', 'Implementación de autenticación JWT', 'Documentación con Swagger', 'Containerización con Docker'],
    technicalDecisions: ['JWT sobre sessions por escalabilidad horizontal', 'PostgreSQL sobre MongoDB por integridad relacional'],
    methodology: 'Kanban personal con issues en Gitea',
    versionControl: 'Git Flow con ramas feature/, fix/ y main',
    testing: 'Tests de integración con Jest sobre los endpoints principales',
    metrics: ['100% de endpoints documentados', 'Tiempo de respuesta promedio < 80ms'],
    problemSolved: 'Centralizar la lógica de negocio en un solo servicio consumible por múltiples clientes.',
    status: 'En producción',
    challenges: ['Diseñar rutas escalables desde el inicio', 'Manejar refresh tokens sin comprometer la UX'],
    learnings: ['Importancia de definir contratos de API antes de codear', 'Cómo estructurar middlewares sin acoplarlos al negocio'],
    repo: '#',
    demo: '#',
  },
  {
    image: 'app.webp',
    title: 'App Mobile',
    description: 'Aplicación móvil multiplataforma.',
    date: 'Mar 2026',
    type: 'Freelance',
    client: 'Cliente privado',
    duration: '4 meses',
    teamSize: '2 personas',
    stack: ['React Native', 'Expo', 'TypeScript', 'Zustand', 'REST API'],
    architecture: 'Componentes reutilizables con estado global en Zustand y navegación por stacks.',
    integrations: ['API REST propia', 'Notificaciones push con Expo', 'Almacenamiento local con AsyncStorage'],
    role: 'Mobile Developer — lideré la UI y la integración con la API.',
    responsibilities: ['Desarrollo de pantallas principales', 'Integración con API REST', 'Gestión de estado con Zustand', 'Publicación en stores'],
    technicalDecisions: ['Expo sobre bare RN por velocidad de iteración', 'Zustand sobre Redux por simplicidad'],
    methodology: 'Sprints de 2 semanas con revisión semanal con el cliente',
    versionControl: 'Git con ramas por feature y PRs revisados',
    testing: 'Testing manual en dispositivos físicos iOS y Android',
    metrics: ['Lanzada en App Store y Google Play', '4.2 estrellas promedio en reviews'],
    problemSolved: 'Dar acceso móvil a una plataforma que solo existía en web.',
    status: 'En producción',
    challenges: ['Compatibilidad entre iOS y Android en componentes nativos', 'Manejo de estado offline con sincronización automática'],
    learnings: ['Gestión de permisos nativos en distintas versiones de SO', 'Optimización de FlatList en listas largas'],
    repo: '#',
    demo: '#',
  },
  {
    image: 'cliente.webp',
    title: 'Portal Cliente',
    description: 'Portal web para gestión de clientes.',
    date: 'Feb 2026',
    type: 'Laboral',
    client: 'Empresa interna',
    duration: '2 meses',
    teamSize: '3 personas',
    stack: ['Angular', 'TypeScript', 'RxJS', 'Angular Material', 'Spring Boot'],
    architecture: 'Frontend Angular con arquitectura modular por feature, backend Spring Boot en capas.',
    integrations: ['Spring Boot API', 'Auth con Keycloak', 'Exportación a PDF'],
    role: 'Frontend Lead — arquitecté el módulo de gestión y los flujos de navegación.',
    responsibilities: ['Arquitectura del frontend', 'Módulo de gestión de clientes', 'Integración con API de Spring Boot', 'Gestión de roles en UI'],
    technicalDecisions: ['Angular Material por consistencia con otros proyectos del equipo', 'Keycloak por requerimiento de empresa'],
    methodology: 'Scrum con sprints de 2 semanas y daily meetings',
    versionControl: 'Git Flow con feature branches y code review obligatorio',
    testing: 'Unit tests con Karma/Jasmine en servicios críticos',
    metrics: ['Reducción del 40% en tiempo de gestión administrativa', '3 módulos entregados a tiempo'],
    problemSolved: 'Reemplazar un proceso manual en Excel por un portal centralizado.',
    status: 'En producción',
    challenges: ['Sincronización en tiempo real entre múltiples usuarios', 'Sistema de permisos por rol sin complejidad en UI'],
    learnings: ['Uso avanzado de RxJS para combinar streams', 'Diseño de sistemas de roles que escalen'],
    repo: '#',
    demo: '#',
  },
  {
    image: 'ecommerce.webp',
    title: 'E-Commerce',
    description: 'Tienda online con carrito y pagos integrados.',
    date: 'Jan 2026',
    type: 'Freelance',
    client: 'Tienda local',
    duration: '3 meses',
    teamSize: 'Solo',
    stack: ['Next.js', 'TypeScript', 'Stripe', 'Prisma', 'PostgreSQL'],
    architecture: 'Full Stack con Next.js App Router, API Routes y Prisma como ORM.',
    integrations: ['Stripe para pagos', 'Webhooks de Stripe', 'Cloudinary para imágenes'],
    role: 'Desarrollador Full Stack — implementé el flujo completo de compra y la integración con Stripe.',
    responsibilities: ['Catálogo de productos', 'Carrito y checkout', 'Integración con Stripe', 'Panel de administración'],
    technicalDecisions: ['Next.js App Router por SSR nativo', 'Prisma sobre Drizzle por madurez del ecosistema'],
    methodology: 'Kanban con Trello, entregas semanales al cliente',
    versionControl: 'Git con main protegido y deploys automáticos en Vercel',
    testing: 'Tests E2E con Playwright para el flujo de compra',
    metrics: ['Tiempo de carga < 1.5s en mobile', 'Tasa de conversión 3.2% en primer mes'],
    problemSolved: 'Digitalizar las ventas de una tienda física sin infraestructura digital previa.',
    status: 'En producción',
    challenges: ['Consistencia entre stock y pedidos en concurrencia', 'Webhooks de Stripe confiables'],
    learnings: ['Transacciones atómicas con Prisma', 'Patrones de idempotencia para pagos sin duplicados'],
    repo: '#',
    demo: '#',
  },
  {
    image: 'gitea.webp',
    title: 'Gitea',
    description: 'Servidor Git self-hosted con CI/CD.',
    date: 'Dec 2025',
    type: 'Proyecto personal',
    client: 'Uso propio',
    duration: '1 mes',
    teamSize: 'Solo',
    stack: ['Gitea', 'Docker', 'Nginx', 'Woodpecker CI', 'Linux'],
    architecture: 'Servidor self-hosted con Nginx como reverse proxy y Docker Compose para orquestación.',
    integrations: ['Woodpecker CI para pipelines', 'Nginx para HTTPS', 'Certbot para certificados'],
    role: 'DevOps — configuré el servidor, pipelines de CI/CD y políticas de acceso.',
    responsibilities: ['Instalación y configuración de Gitea', 'Setup de Nginx + HTTPS', 'Pipelines de CI/CD con Woodpecker', 'Backups automáticos'],
    technicalDecisions: ['Gitea sobre GitLab por menor consumo de recursos', 'Woodpecker por integración nativa con Gitea'],
    methodology: 'Implementación iterativa con documentación propia',
    versionControl: 'Git en el propio servidor Gitea',
    testing: 'Smoke tests manuales tras cada deploy de pipeline',
    metrics: ['100% uptime en 3 meses de operación', 'Pipelines ejecutan en < 2 minutos'],
    problemSolved: 'Tener control total del código fuente sin depender de GitHub ni servicios externos.',
    status: 'En producción',
    challenges: ['HTTPS con certificados propios en red interna', 'Pipelines en runners Docker aislados'],
    learnings: ['Administración de servidores Linux en producción', 'Diseño de pipelines CI/CD reproducibles'],
    repo: '#',
    demo: '#',
  },
  {
    image: 'nafa.webp',
    title: 'Nafa',
    description: 'Web Site Administrable.',
    date: 'Aug 2025',
    type: 'Freelance',
    client: 'Nafa',
    duration: '2 meses',
    teamSize: 'Solo',
    stack: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'MongoDB'],
    architecture: 'CMS headless con panel admin separado del sitio público, API REST en Node.js.',
    integrations: ['Cloudinary para imágenes', 'MongoDB Atlas en la nube', 'Vercel para deploy'],
    role: 'Desarrollador Full Stack — desarrollé el CMS personalizado y el sitio público.',
    responsibilities: ['Sitio público con React', 'Panel de administración', 'API REST para el CMS', 'Sistema de uploads de imágenes'],
    technicalDecisions: ['CMS propio sobre WordPress por control total del diseño', 'MongoDB por flexibilidad en el modelo de contenido'],
    methodology: 'Entregas iterativas con feedback del cliente cada semana',
    versionControl: 'Git con deploys automáticos desde main',
    testing: 'Testing manual con el cliente en staging antes de cada release',
    metrics: ['El cliente gestiona el contenido 100% sin soporte técnico', 'Carga inicial < 2s'],
    problemSolved: 'Dar autonomía al cliente para actualizar su sitio sin conocimientos técnicos.',
    status: 'En producción',
    challenges: ['Editor de contenido intuitivo sin librerías pesadas', 'Optimización de imágenes cargadas por el admin'],
    learnings: ['Arquitectura de CMS headless a pequeña escala', 'Manejo de uploads y transformación de imágenes en servidor'],
    repo: '#',
    demo: '#',
  },
];

export const integrationIconMap: Record<string, string> = {
  'jwt':            '🔑',
  'auth':           '🔐',
  'keycloak':       '🔐',
  'docker':         '🐳',
  'swagger':        '📄',
  'pdf':            '📄',
  'docs':           '📄',
  'expo':           '📱',
  'push':           '🔔',
  'notif':          '🔔',
  'async':          '💾',
  'storage':        '💾',
  'cloudinary':     '☁️',
  'cloud':          '☁️',
  'vercel':         '🚀',
  'deploy':         '🚀',
  'stripe':         '💳',
  'pago':           '💳',
  'webhook':        '🔗',
  'api':            '⚡',
  'rest':           '⚡',
  'spring':         '⚙️',
  'nginx':          '🌐',
  'web':            '🌐',
  'certbot':        '🔒',
  'https':          '🔒',
  'cert':           '🔒',
  'woodpecker':     '🔄',
  'ci':             '🔄',
  'mongodb':        '🗄️',
  'postgres':       '🗄️',
  'db':             '🗄️',
  'atlas':          '🗄️',
};

export const techIcons: Record<string, string> = {
  'Angular':        '/Brayan/svg/angular.svg',
  'React':          '/Brayan/svg/reactjs-svgrepo-com.svg',
  'React Native':   '/Brayan/svg/reactjs-svgrepo-com.svg',
  'Next.js':        '/Brayan/svg/nextjs-icon.svg',
  'TypeScript':     '/Brayan/svg/typescript-svgrepo-com.svg',
  'Tailwind CSS':   '/Brayan/svg/tailwind-svgrepo-com.svg',
  'Spring Boot':    '/Brayan/svg/spring.svg',
  'Git':            '/Brayan/svg/git-svgrepo-com.svg',
  'Vite':           '/Brayan/svg/vitejs-svgrepo-com.svg',
  'Python':         '/Brayan/svg/python.svg',
  'Java':           '/Brayan/svg/java.svg',
  'CSS':            '/Brayan/svg/css-svgrepo-com.svg',
  'HTML':           '/Brayan/svg/file-type-html.svg',
  'Bash':           '/Brayan/svg/bash-icon.svg',
};

export const techCategories: Record<string, string> = {
  'Angular':          'Frontend',
  'React':            'Frontend',
  'React Native':     'Mobile',
  'Next.js':          'Frontend',
  'TypeScript':       'Lenguaje',
  'Tailwind CSS':     'Estilos',
  'Spring Boot':      'Backend',
  'Node.js':          'Backend',
  'Express':          'Backend',
  'Python':           'Backend',
  'Java':             'Backend',
  'PostgreSQL':       'Base de datos',
  'MongoDB':          'Base de datos',
  'Prisma':           'ORM',
  'JWT':              'Auth',
  'Docker':           'DevOps',
  'Nginx':            'DevOps',
  'Linux':            'DevOps',
  'Git':              'Control de versiones',
  'Gitea':            'DevOps',
  'Woodpecker CI':    'CI/CD',
  'Swagger':          'Documentación',
  'Stripe':           'Pagos',
  'RxJS':             'Reactividad',
  'Zustand':          'Estado',
  'Expo':             'Mobile',
  'Cloudinary':       'Storage',
  'Keycloak':         'Auth',
  'Angular Material': 'UI',
  'REST API':         'API',
  'Vite':             'Bundler',
};
